global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'postgresql'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 192.168.1.48:9187
        labels:
          alias: postgres
