global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'postgresql'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 192.168.1.45:9187
        labels:
          alias: postgres
  - job_name: 'spring_micrometr'
    metrics_path: 'actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 192.168.1.45:8000
        labels:
          alias: actuator
